src/ModernRecrut.MVC/Controllers/FavorisController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;
using ModernRecrut.MVC.Models.Log;
using System;
using System.Net;
using System.Web;

namespace ModernRecrut.MVC.Controllers
{
    public class FavorisController : Controller
    {
        private readonly IFavorisService _favorisService;
        private readonly IOffreEmploiService _offreEmploiService;
        private readonly ILogger<FavorisController> _logger;
        public FavorisController(IFavorisService favorisService, IOffreEmploiService offreEmploiService, ILogger<FavorisController> logger)
        {
            _favorisService = favorisService;
            _offreEmploiService = offreEmploiService;
            _logger = logger;
        }

        // GET: FavorisController
        public async Task<IActionResult> Index()
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            IEnumerable<OffreEmploi> offresEmploi = await _favorisService.ObtenirTout(ip);
            return offresEmploi != null ?
                        View(offresEmploi) :
                        Problem(" 'offresEmploi' est null.");
            
        }
        public async Task<ActionResult> Details(int id)
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            OffreEmploi offre = await _favorisService.ObtenirSelonId(id, ip);
            if (offre == null)
            {
                return NotFound();
            }
            return View(offre);
        }

        // GET: FavorisController/Create
        public async Task<ActionResult> Create(int id)
        {
            
            OffreEmploi offre = await _offreEmploiService.ObtenirSelonId(id);
            if (offre == null)
            {
                return NotFound();
            }
            return View(offre);
        }

        //POST: FavorisController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OffreEmploiID,Nom,Poste,Description,DateAffichage,DateFin")] OffreEmploi offre)
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            IEnumerable<OffreEmploi> offresEmploi = await _favorisService.ObtenirTout(ip);
            if (offresEmploi.Any(o => o.OffreEmploiID == offre.OffreEmploiID))
            {
                ModelState.AddModelError("OffreEmploiID", "Cette offre est déjà dans vos favoris");
            }
            if (ModelState.IsValid)
            {

                await _favorisService.Ajouter(offre, ip);
                _logger.LogInformation(FavoriLog.Ajout, $"Ajout d'un favoris. ID = {offre.OffreEmploiID}");
                _logger.LogError($"Une erreur c'est produite lors de la création d'un favoris. ID = {offre.OffreEmploiID}");
                _logger.LogCritical($"L'application a rencontré un problème critique lors de la création d'un favoris. ID = {offre.OffreEmploiID}");

                return RedirectToAction(nameof(Index));
            }
            return View(offre);

        }
        //GET: FavorisController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            OffreEmploi offre = await _favorisService.ObtenirSelonId(id, ip);
;            if (offre == null)
            {
                return NotFound();
            }
            return View(offre);
        }

        //POST: FavorisController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int offreEmploiID, OffreEmploi offre)
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            await _favorisService.Supprimer(offreEmploiID, ip);
            _logger.LogInformation(FavoriLog.Suppression, $"Suppression d'un favoris. ID = {offreEmploiID}");
            _logger.LogError($"Une erreur c'est produite lors de la suppression d'un favoris. ID = {offreEmploiID}");
            _logger.LogCritical($"L'application a rencontré un problème critique lors de la suppression d'un favoris. ID = {offreEmploiID}");
            
            return RedirectToAction(nameof(Index));
        }
    }
}

src/ModernRecrut.MVC/Controllers/OffreEmploiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;
using ModernRecrut.MVC.Models.Log;
using System.Data;

namespace ModernRecrut.MVC.Controllers
{
    [Authorize(Roles = "RH, Admin")]
    public class OffreEmploiController : Controller
    {

        private readonly IOffreEmploiService _offreEmploiService;
        private readonly ILogger<OffreEmploiController> _logger;

        public OffreEmploiController(IOffreEmploiService offreEmploiService, ILogger<OffreEmploiController> logger)
        {
            _offreEmploiService = offreEmploiService;
            _logger = logger;
        }

        [AllowAnonymous]
        // GET: OffreEmploiController
        public async Task<IActionResult> Index(string filtre)
        {
            if (filtre is null)
            {
                return View(await _offreEmploiService.ObtenirTout());
            }
            ViewData["actifFiltre"] = filtre;

            List<OffreEmploi> offresEmploi = await _offreEmploiService.OffresFiltrer(filtre);

            return offresEmploi != null ?
                        View(offresEmploi) :
                        Problem("Entité set 'offresEmploi' est null.");
        }

        [AllowAnonymous]
        // GET: OffreEmploiController/Details/5
        public async Task<IActionResult> Details(int id)
        {
            OffreEmploi offreEmploi = await _offreEmploiService.ObtenirSelonId(id);

            if (offreEmploi == null)
            {
                _logger.LogError($"Une erreur c'est produite lors de la récupération d'une offre d'emploi. ID = {offreEmploi.OffreEmploiID}");
                return NotFound();

            }
            return View(offreEmploi);
        }

        // GET: OffreEmploiController/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: OffreEmploiController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OffreEmploiID,Nom,Poste,Description,DateAffichage,DateFin")] OffreEmploi offreEmploi)
        {
            if (ModelState.IsValid)
            {
                await _offreEmploiService.Ajouter(offreEmploi);
                _logger.LogInformation(OffreEmploiLog.Creation, $"Creation d'une offre. ID = {offreEmploi.OffreEmploiID}");
                
                _logger.LogCritical($"L'application a rencontré un problème critique lors de la création d'une offre d'emploi. ID = {offreEmploi.OffreEmploiID}"); 
                
                return RedirectToAction(nameof(Index));
            }
            _logger.LogError($"Une erreur c'est produite lors de la création d'une offre d'emploi. ID = {offreEmploi.OffreEmploiID}");
            return View(offreEmploi);
        }

        // GET: OffreEmploiController/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            OffreEmploi offreEmploi = await _offreEmploiService.ObtenirSelonId(id);

            if (offreEmploi == null)
            {
                _logger.LogError($"Une erreur c'est produite lors de la récupération d'une offre d'emploi. ID = {offreEmploi.OffreEmploiID}");
                return NotFound();
            }
            return View(offreEmploi);
        }

        // POST: OffreEmploiController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OffreEmploiID,Nom,Poste,Description,DateAffichage,DateFin")] OffreEmploi offreEmploi)
        {
            if (offreEmploi == null)
            {
                _logger.LogError($"Une erreur c'est produite lors de la modification d'une offre d'emploi. ID = {offreEmploi.OffreEmploiID}");
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _offreEmploiService.Modifier(offreEmploi);
                _logger.LogInformation(OffreEmploiLog.Modication, $"Modification d'une offre. ID = {offreEmploi.OffreEmploiID}");
                
                _logger.LogCritical($"L'application a rencontré un problème critique lors de la modification d'une offre d'emploi. ID = {offreEmploi.OffreEmploiID}"); 
                
                return RedirectToAction(nameof(Index));
            }

            return View(offreEmploi);
        }

        // GET: OffreEmploiController/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            OffreEmploi offreEmploi = await _offreEmploiService.ObtenirSelonId(id);

            if (offreEmploi == null)
            {
                _logger.LogError($"Une erreur c'est produite lors de la récupération d'une offre d'emploi. ID = {offreEmploi.OffreEmploiID}");
                return NotFound();
            }
            return View(offreEmploi);
        }

        // POST: OffreEmploiController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, OffreEmploi offreEmploi)
        {
            offreEmploi = await _offreEmploiService.ObtenirSelonId(id);
            if (offreEmploi == null)
            {
                _logger.LogError($"Une erreur c'est produite lors de la récupération d'une offre d'emploi. ID = {offreEmploi.OffreEmploiID}");
                return NotFound();
            }
            await _offreEmploiService.Supprimer(offreEmploi);
            _logger.LogInformation(OffreEmploiLog.Suppression, $"Suppression d'une offre. ID = {offreEmploi.OffreEmploiID}");
            _logger.LogCritical($"L'application a rencontré un problème critique lors de la suppression d'une offre d'emploi. ID = {offreEmploi.OffreEmploiID}"); 
            
            return RedirectToAction(nameof(Index));
        }
    }
}

src/ModernRecrut.MVC/Views/Favoris/Create.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Create";
}

<h1>Ajouter aux favoris ?</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
                <input asp-for="OffreEmploiID" class="form-control" hidden />
                
                <input asp-for="Nom" class="form-control" hidden/>
                <input asp-for="Poste" class="form-control" hidden />
                <input asp-for="Description" class="form-control" hidden />
                <input asp-for="DateAffichage" class="form-control" hidden />
                <input asp-for="DateFin" class="form-control" hidden />
            <div class="form-group">
                <input type="submit" value="Ajouter" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/ModernRecrut.MVC/Views/Favoris/Delete.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Delete";
}

<h1>Supprimer</h1>

<h3>Etes-vous sure de vouloir supprimer ce favoris ?</h3>
<div>
    <h4>OffreEmploi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OffreEmploiID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OffreEmploiID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAffichage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAffichage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OffreEmploiID" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste des favoris</a>
    </form>
</div>

src/ModernRecrut.MVC/Views/Favoris/Details.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Details";
}

<h1>Détails</h1>

<div>
    <h4>Offre Emploi Favoris</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OffreEmploiID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OffreEmploiID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAffichage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAffichage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Supprimer", "Delete", new { id=Model.OffreEmploiID }) |
    <a asp-action="Index">Retour aux Favoris</a> |
    <a asp-action="Index", asp-controller="OffreEmploi">Liste des Offres</a>
</div>

src/ModernRecrut.MVC/Views/Favoris/Index.cshtml
@model IEnumerable<ModernRecrut.MVC.Models.OffreEmploi>

@{
    ViewData["Title"] = "Index";
}

<h1>Liste des Favoris</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OffreEmploiID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poste)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAffichage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateFin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.OffreEmploiID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nom)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Poste)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAffichage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateFin)
            </td>
            <td>
                    @Html.ActionLink("Détails", "Details", new { id=item.OffreEmploiID }) |
                    @Html.ActionLink("Supprimer", "Delete", new { id=item.OffreEmploiID })
            </td>
        </tr>
}
    </tbody>
</table>