src/ModernRecrut.MVC/Models/OffreEmploi.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Text.Json.Serialization;

namespace ModernRecrut.MVC.Models
{
    public class OffreEmploi
    {
        [JsonPropertyName("id")]
        public int OffreEmploiID { get; set; }
        [Required(ErrorMessage = "Veuillez renseigner le nom de l'offre d'emploi")]
        public string Nom { get; set; }
        [Required(ErrorMessage = "Veuillez renseigner le poste de l'offre d'emploi")]
        public string Poste { get; set; }
        [Required(ErrorMessage = "Veuillez renseigner la description de l'offre d'emploi")]
        public string Description { get; set; }
        [DisplayName("Date d'affichage"), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}"), Required(ErrorMessage = "Veuillez renseigner la date d'affichage de l'offre d'emploi")]
        public DateTime DateAffichage { get; set; }
        [DisplayName("Date de Fin"), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}"), Required(ErrorMessage = "Veuillez renseigner la date de fin de l'offre d'emploi")]
        public DateTime DateFin { get; set; }
    }
}

src/ModernRecrut.MVC/Controllers/FavorisController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;
using ModernRecrut.MVC.Models.Log;
using System;
using System.Net;
using System.Web;

namespace ModernRecrut.MVC.Controllers
{
    public class FavorisController : Controller
    {
        private readonly IFavorisService _favorisService;
        private readonly IOffreEmploiService _offreEmploiService;
        private readonly ILogger<FavorisController> _logger;
        public FavorisController(IFavorisService favorisService, IOffreEmploiService offreEmploiService, ILogger<FavorisController> logger)
        {
            _favorisService = favorisService;
            _offreEmploiService = offreEmploiService;
            _logger = logger;
        }

        // GET: FavorisController
        public async Task<IActionResult> Index()
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            IEnumerable<OffreEmploi> offresEmploi = await _favorisService.ObtenirTout(ip);
            return offresEmploi != null ?
                        View(offresEmploi) :
                        Problem(" 'offresEmploi' est null.");
            
        }
        public async Task<ActionResult> Details(int id)
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            OffreEmploi offre = await _favorisService.ObtenirSelonId(id, ip);
            if (offre == null)
            {
                return NotFound();
            }
            return View(offre);
        }

        // GET: FavorisController/Create
        public async Task<ActionResult> Create(int id)
        {
            
            OffreEmploi offre = await _offreEmploiService.ObtenirSelonId(id);
            if (offre == null)
            {
                return NotFound();
            }
            return View(offre);
        }

        //POST: FavorisController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OffreEmploiID,Nom,Poste,Description,DateAffichage,DateFin")] OffreEmploi offre)
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            IEnumerable<OffreEmploi> offresEmploi = await _favorisService.ObtenirTout(ip);
            if (offresEmploi.Any(o => o.OffreEmploiID == offre.OffreEmploiID))
            {
                ModelState.AddModelError("OffreEmploiID", "Cette offre est déjà dans vos favoris");
            }
            if (ModelState.IsValid)
            {

                await _favorisService.Ajouter(offre, ip);
                _logger.LogInformation(FavoriLog.Ajout, $"Ajout d'un favoris. ID = {offre.OffreEmploiID}");
                _logger.LogError($"Une erreur c'est produite lors de la création d'un favoris. ID = {offre.OffreEmploiID}");
                _logger.LogCritical($"L'application a rencontré un problème critique lors de la création d'un favoris. ID = {offre.OffreEmploiID}");

                return RedirectToAction(nameof(Index));
            }
            return View(offre);

        }
        //GET: FavorisController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            OffreEmploi offre = await _favorisService.ObtenirSelonId(id, ip);
;            if (offre == null)
            {
                return NotFound();
            }
            return View(offre);
        }

        //POST: FavorisController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int offreEmploiID, OffreEmploi offre)
        {
            string? ip = Request.HttpContext.Connection.RemoteIpAddress?.ToString();
            if (ip == null)
            {
                return BadRequest();
            }
            await _favorisService.Supprimer(offreEmploiID, ip);
            _logger.LogInformation(FavoriLog.Suppression, $"Suppression d'un favoris. ID = {offreEmploiID}");
            _logger.LogError($"Une erreur c'est produite lors de la suppression d'un favoris. ID = {offreEmploiID}");
            _logger.LogCritical($"L'application a rencontré un problème critique lors de la suppression d'un favoris. ID = {offreEmploiID}");
            
            return RedirectToAction(nameof(Index));
        }
    }
}

src/ModernRecrut.MVC/Controllers/PostulationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using ModernRecrut.MVC.Areas.Identity.Data;
using ModernRecrut.MVC.Interfaces;
using ModernRecrut.MVC.Models;
using ModernRecrut.MVC.Models.DTO;
using ModernRecrut.MVC.Models.Log;

namespace ModernRecrut.MVC.Controllers
{
    [Authorize]
    public class PostulationsController : Controller
    {
        private readonly IPostulationService _postulationService;
        private readonly ILogger<PostulationsController> _logger;
        public PostulationsController(ILogger<PostulationsController> logger, IPostulationService postulationService)
        {
            _logger = logger;
            _postulationService = postulationService;
        }
        [Authorize(Roles = "Employe, Admin")]
        // GET: Postulation
        public async Task<ActionResult> ListePostulations()
        {
            IEnumerable<ListePostulationVueModel> postulations = await _postulationService.ObtenirTout();

            if (postulations != null)
            {
                _logger.LogInformation(PostulationLog.Lecture, $"Lecture de {postulations.Count()} postulations");
                return View(postulations);
            }
            return Problem("postulations introuvables.");
        }
        [Authorize(Roles = "RH, Admin")]
        public async Task<ActionResult> Notes()
        {
            
            _logger.LogInformation(PostulationLog.Notation, "Notation d'une postulation");
            return View();
        }
        [Authorize(Roles = "Candidat, Admin")]
        // GET: Postulation/Create
        public async Task<ActionResult> Postuler(int Id)
        {
            Utilisateur utilisateur = await _postulationService.ObtenirUtilisateur(User.Identity.Name);
            Postulation postulation = new Postulation { IdCandidat= utilisateur.Id, OffreEmploiID = Id};
            postulation.IdCandidat = utilisateur.Id;
            return View(postulation);
        }
        [Authorize(Roles = "Candidat, Admin")]
        // POST: Postulation/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Postuler([Bind("IdCandidat,OffreEmploiID,PretentionSalariale,DateDisponibilite,Notes")] Postulation postulation)
        {
            //ajouter validation date et prétention salariale

            await Validations_Postulation(postulation);
            Validations(postulation);
            if (ModelState.IsValid)
            {
                await _postulationService.Ajouter(postulation);
                _logger.LogInformation(PostulationLog.Postulation, "Postulation d'un candidat");
                return RedirectToAction(nameof(Index), controllerName: "OffreEmploi");
            }
            return View(postulation);
        }

        [Authorize(Roles = "RH, Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            Postulation postulation = await _postulationService.ObtenirSelonId(id);

            if (postulation == null)
            {
                _logger.LogError($"Une erreur s'est produite lors de la récupération d'une postulation. ID = {id}");
                return NotFound();
            }
            return View(postulation);
        }

        //[Authorize(Roles = "RH, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind("Id,IdCandidat,OffreEmploiID,PretentionSalariale,DateDisponibilite,Notes")] Postulation postulation)
        {
            if (postulation == null)
            {
                _logger.LogError($"Une erreur s'est produite lors de la modification d'une postulation.");
                return NotFound();
            }

            ValidationDate_Modification_Supression(postulation.DateDisponibilite);
            Validations(postulation);
            if (ModelState.IsValid)
            {
                await _postulationService.Modifier(postulation);
                _logger.LogInformation(PostulationLog.Modification, $"Modification d'une postulation. ID = {postulation.Id}");
                return RedirectToAction(nameof(ListePostulations));
            }
            return View(postulation);
        }


        [Authorize(Roles = "RH, Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            Postulation postulation = await _postulationService.ObtenirSelonId(id);

            if (postulation == null)
            {
                _logger.LogError($"Une erreur c'est produite lors de la récupération d'une postulation. id recherché : {id}");
                return NotFound();
            }
            return View(postulation);
        }

        [Authorize(Roles = "RH, Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Postulation postulation)
        {
            postulation = await _postulationService.ObtenirSelonId(postulation.Id);
            if (postulation == null)
            {
                _logger.LogError($"Une erreur c'est produite lors de la récupération d'une offre d'emploi.");
                return NotFound();
            }
            ValidationDate_Modification_Supression(postulation.DateDisponibilite);
            if (ModelState.IsValid)
            {
                await _postulationService.Supprimer(postulation.Id);
                _logger.LogInformation(PostulationLog.Suppression, $"Suppression d'une postulation. ID = {postulation.OffreEmploiID}");
                return RedirectToAction("ListePostulations");
            }
            return View(postulation);
        }





        //Ajouter methode Delete avec verification date
        private async Task Validations_Postulation(Postulation postulation)
        {
            if (!await _postulationService.CandidatPossedeLettre(postulation.IdCandidat))
            {
                ModelState.AddModelError("", "Vous devez déposer une lettre pour Postuler");
            }
            if (!await _postulationService.CandidatPossedeCV(postulation.IdCandidat))
            {
                ModelState.AddModelError("", "Vous devez déposer un CV pour Postuler");
            }
        }
        private void Validations(Postulation postulation)
        {
            
            if (_postulationService.PretentionsSalarialeTropElever(postulation.PretentionSalariale))
            {
                ModelState.AddModelError("PretentionSalariale", "Votre prétention salariale est au-delà de nos limites");
            }
            if (_postulationService.DateDisponibiliteIncorecte(postulation.DateDisponibilite))
            {
                ModelState.AddModelError("", $"La date de disponibilité doit être supérieure à {DateTime.Now:MM/dd/yyyy} et inférieure au {DateTime.Now.AddDays(45):MM/dd/yyyy}");
            }
        }
        private void ValidationDate_Modification_Supression(DateTime date)
        {
            if (_postulationService.DateIncorectePour_Modification_Supression(date))
            {
                ModelState.AddModelError("", "La postulation ne peut pas être modifiée car la date de l'entrevue est proche.");
            }
        }
    }
}

src/ModernRecrut.MVC/Views/OffreEmploi/Create.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Create";
}

<h1>Ajouter</h1>

<h4>Offre Emploi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poste" class="control-label"></label>
                <input asp-for="Poste" class="form-control" />
                <span asp-validation-for="Poste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAffichage" class="control-label"></label>
                <input asp-for="DateAffichage" class="form-control" type="date"/>
                <span asp-validation-for="DateAffichage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFin" class="control-label"></label>
                <input asp-for="DateFin" class="form-control" type="date" />
                <span asp-validation-for="DateFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/ModernRecrut.MVC/Views/OffreEmploi/Delete.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Delete";
}

<h1>Supprimer</h1>

<h3>Etes-vous sure de vouloir supprimer cet emprunt ?</h3>
<div>
    <h4>Offre Emploi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OffreEmploiID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OffreEmploiID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAffichage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAffichage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OffreEmploiID" />
        <input type="submit" value="Supprimer" class="btn btn-danger" /> |
        <a asp-action="Index">Retour à la liste</a>
    </form>
</div>

src/ModernRecrut.MVC/Views/OffreEmploi/Details.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Details";
}

<h1>Détails</h1>

<div>
    <h4>Offre Emploi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.OffreEmploiID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.OffreEmploiID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Poste)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Poste)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateAffichage)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateAffichage)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateFin)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateFin)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Modifier", "Edit", new { id = Model.OffreEmploiID}) |
    @Html.ActionLink("Postuler", "Postuler", "Postulations", new { id = Model.OffreEmploiID}) |
    @Html.ActionLink("Ajouter aux Favoris", "Create", "Favoris", new { id = Model.OffreEmploiID}) |
    <a asp-action="Index">Retour à la liste</a>
</div>

src/ModernRecrut.MVC/Views/OffreEmploi/Edit.cshtml
@model ModernRecrut.MVC.Models.OffreEmploi

@{
    ViewData["Title"] = "Edit";
}

<h1>Modifier</h1>

<h4>Offre Emploi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OffreEmploiID" />
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Poste" class="control-label"></label>
                <input asp-for="Poste" class="form-control" />
                <span asp-validation-for="Poste" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateAffichage" class="control-label"></label>
                <input asp-for="DateAffichage" class="form-control" />
                <span asp-validation-for="DateAffichage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateFin" class="control-label"></label>
                <input asp-for="DateFin" class="form-control" />
                <span asp-validation-for="DateFin" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retour à la liste</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/ModernRecrut.MVC/Views/OffreEmploi/Index.cshtml
@model IEnumerable<ModernRecrut.MVC.Models.OffreEmploi>

@{
    ViewData["Title"] = "Index";
}

<h1>Offres Emploi</h1>

<p>
    <a asp-action="Create">Ajouter nouveau</a>
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Recherche offre emploi: <input type="text" name="filtre" value="@ViewData["actifFiltre"]" />
            <input type="submit" value="Recherche" class="btn btn-default" />
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OffreEmploiID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Poste)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAffichage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateFin)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.OffreEmploiID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Poste)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateAffichage)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateFin)
                </td>
                <td>
                    @Html.ActionLink("Modifier", "Edit", new { id=item.OffreEmploiID }) |
                    @Html.ActionLink("Détails", "Details", new { id=item.OffreEmploiID }) |
                    @Html.ActionLink("Supprimer", "Delete", new { id=item.OffreEmploiID })
                </td>
            </tr>
        }
    </tbody>
</table>